### ISSUE TITLE
react-native-video:processReleaseResources FAILED

### ISSUE THREAD

**Issue by qpixHassaballah** [aakashns/ReactMusic#1]
Error is while trying to build the apk on android phone .
I am just following the readme steps but the app does not run because the build fails

**Comment by umangshah-js** [comment]
> Error is while trying to build the apk on android phone .
> I am just following the readme steps but the app does not run because the build fails

+1

**Comment by Waqas-Jani** [comment]
![screenshot from 2018-10-21 12-28-54](https://user-images.githubusercontent.com/38995824/47264270-017cc980-d52d-11e8-8d46-976f8ad7e11f.png)
please help me to solve this error

**Comment by bassman2112** [comment]
@Waqas-Jani 

Sorry this is many months later! I can't speak for the first two errors in this thread, but the one you are encountering is fixed by replacing `var Slider = require('react-native-slider');` in **SeekBar.js** with `import Slider from '@react-native-community/slider';`

You'll also have to run `npm install @react-native-community/slider --save` and `react-native link @react-native-community/slider`

Hope that helps!

**Comment by shubham-akole** [comment]
i got same issue like @Waqas-Jani. i tried to solve using your solution but still not solve.
